### PR TITLE
UI Tweaks

### PR DESCRIPTION
**Pull request by ytt3r**
Lookin' good! (I'm not entirely sure what I was saying when I said it would make future UI updates easier :P)

### CODE REVIEW

**Comment by xcaliburinhand** [comment]
There is an issue with landscape mode, any way to get everything to reposition on landscape, or scrolling enabled.

**Comment by ytt3r** [comment]
I'll work on it tomorrow.
(edit-done)

**Comment by ytt3r** [comment]
you should be good to go xcal, just pull it in if you want ;)

**Comment by xcaliburinhand** [comment]
commits squashed and imported.

**Pull request closed without merging**
